import BankTransfer from './BankTransfer.vue'
 import BankTransfers from './BankTransfers.vue'
 const bankTransferNav={ routes:[
        {
                path: '/banktransfer/:mode',
                name: 'banktransfer',
                component: BankTransfer,
                meta: { auth: true },
         },
         {
                path: '/banktransfers',
                name: 'banktransfers',
                component: BankTransfers,
                meta: { auth: true },
         },
        
        ],
menu:{id: "banking.banktransfer",
        title: "Bank Transfers",
        component: BankTransfer,
        path: "banktransfers",
        width: "1000px",
editHeaders: [{ title: "From Account Type", key: "fromAccountType"    },
{ title: "From Account", key: "fromAccount" ,isNumeric: true   },
{ title: "From Currency", key: "fromCurrencyId" ,isNumeric: true   },
{ title: "To Account Type", key: "toAccountType"    },
{ title: "To Account", key: "toAccount" ,isNumeric: true   },
{ title: "To Currency", key: "toCurrencyId" ,isNumeric: true   },
{ title: "Reference No", key: "referenceNo"    },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount Tendered", key: "amountTendered" ,isNumeric: true   },
{ title: "Transfer Charge", key: "transferCharge" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Transfer Date", key: "transferDate"  , isDate: true },
{ title: "Notes", key: "notes"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "From Account Type", key: "fromAccountType"    },
{ title: "From Account", key: "fromAccount" ,isNumeric: true   },
{ title: "From Currency", key: "fromCurrencyId" ,isNumeric: true   },
{ title: "To Account Type", key: "toAccountType"    },
{ title: "To Account", key: "toAccount" ,isNumeric: true   },
{ title: "To Currency", key: "toCurrencyId" ,isNumeric: true   },
{ title: "Reference No", key: "referenceNo"    },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount Tendered", key: "amountTendered" ,isNumeric: true   },
{ title: "Transfer Charge", key: "transferCharge" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Transfer Date", key: "transferDate"  , isDate: true },
{ title: "Notes", key: "notes"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "banking.bankTransfer.view", title: "View",  to:{ name: "banktransfers", }},
{ id: "banking.bankTransfer.new", title: "New",  to:{ name: "banktransfer", params: {mode:0}}},
{ id: "banking.bankTransfer.edit", title: "Edit",  to:{ name: "banktransfer", params: {mode:1}}},
{ id: "banking.bankTransfer.history", title: "History",  to:{ name: "banktransfer", params: {mode:2}}},
]}
}
export default bankTransferNav;
