import JournalDetails from './JournalDetails.vue'
 import JournalDetailses from './JournalDetailses.vue'
 const journalDetailsNav={ routes:[
        {
                path: '/journaldetails/:mode',
                name: 'journaldetails',
                component: JournalDetails,
                meta: { auth: true },
         },
         {
                path: '/journaldetailses',
                name: 'journaldetailses',
                component: JournalDetailses,
                meta: { auth: true },
         },
        
        ],
menu:{id: "accounting.journaldetails",
        title: "Journal Detailses",
        component: JournalDetails,
        path: "journaldetailses",
        width: "700px",
editHeaders: [{ title: "Journal", key: "journal"    },
{ title: "Account Id", key: "accountId"    },
{ title: "Account Name", key: "accountName"    },
{ title: "Account Type", key: "accountType"    },
{ title: "Account Action", key: "accountAction"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Notes", key: "notes"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "Journal", key: "journal"    },
{ title: "Account Id", key: "accountId"    },
{ title: "Account Name", key: "accountName"    },
{ title: "Account Type", key: "accountType"    },
{ title: "Account Action", key: "accountAction"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Notes", key: "notes"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "accounting.journalDetails.view", title: "View",  to:{ name: "journaldetailses", }},
{ id: "accounting.journalDetails.new", title: "New",  to:{ name: "journaldetails", params: {mode:0}}},
{ id: "accounting.journalDetails.edit", title: "Edit",  to:{ name: "journaldetails", params: {mode:1}}},
{ id: "accounting.journalDetails.history", title: "History",  to:{ name: "journaldetails", params: {mode:2}}},
]}
}
export default journalDetailsNav;
