import Profile from "./Profile.vue";
import Profiles from "./Profiles.vue";
const profileNav = {
  routes: [
    {
      path: "/profile/:mode",
      name: "profile",
      component: Profile,
      meta: { auth: true },
    },
    {
      path: "/profiles",
      name: "profiles",
      component: Profiles,
      meta: { auth: true },
    },
  ],
  menu: {
    id: "loan.profile",
    title: "Profiles",
    component: Profile,
    path: "profiles",
    width: "1000px",
    editHeaders: [
      { title: "First Name", key: "firstName" },
      { title: "Last Name", key: "lastName" },
      { title: "Other Names", key: "otherNames" },
      { title: "Gender", key: "gender" },
      { title: "Birth Date", key: "birthDate" },
      { title: "Marital Status", key: "maritalStatusId.displayKey" },
      { title: "Marital Status", key: "maritalStatus" },
      { title: "Country", key: "countryId" },
      { title: "Country", key: "country" },
      { title: "Spouse Name", key: "spouseName" },
      { title: "Spouse Contact", key: "spouseContact" },
      { title: "NO Kin", key: "nOKin" },
      { title: "NO Kin Contact", key: "nOKinContact" },
      { title: "Id Type", key: "idTypeId" },
      { title: "Id Type", key: "idType" },
      { title: "Id No", key: "idNo" },
      { title: "Primary Phone No", key: "primaryPhoneNo" },
      { title: "Other Phone Nos", key: "otherPhoneNos" },
      { title: "Email", key: "email" },
      { title: "Home Address", key: "homeAddress" },
      { title: "Residential Address", key: "residentialAddress" },
      { title: "Residence Coordinates", key: "residenceCoordinates" },
      { title: "Address Details", key: "addressDetails" },
      { title: "Join Date", key: "joinDate" },
      { title: "Occupation", key: "occupationId" },
      { title: "Occupation", key: "occupation" },
      { title: "Work Type", key: "workType" },
      { title: "Business Category", key: "businessCategoryId" },
      { title: "Business Category", key: "businessCategory" },
      { title: "Business Description", key: "businessDescriptions" },
      { title: "Designation", key: "designation" },
      { title: "Business Name", key: "businessName" },
      { title: "Business Location", key: "businessLocation" },
      { title: "Work Coordinates", key: "workCoordinates" },

      { title: "Actions", key: "actions" },
    ],

    miniHeaders: [
      { title: "Id", key: "id" },
      { title: "Name", key: "display" },
      { title: "Gender", key: "gender" },
      { title: "Birth Date", key: "birthDate" },
      { title: "Primary Phone No", key: "primaryPhoneNo" },
      { title: "Other Phone Nos", key: "otherPhoneNos" },
      { title: "Email", key: "email" },
      { title: "Home Address", key: "homeAddress" },
      { title: "Residential Address", key: "residentialAddress" },
      { title: "Residence Coordinates", key: "residenceCoordinates" },
      { title: "Address Details", key: "addressDetails" },
    ],
    headers: [
      {
        title: "Id",
        align: "start",
        // sortable: false,
        key: "id",
      },
      { title: "First Name", key: "firstName" },
      { title: "Last Name", key: "lastName" },
      { title: "Other Names", key: "otherNames" },
      { title: "Gender", key: "gender" },
      { title: "Country", key: "country" },
      { title: "Id Type", key: "idType" },
      { title: "Id No", key: "idNo" },
      { title: "Primary Phone No", key: "primaryPhoneNo" },
      { title: "Other Phone Nos", key: "otherPhoneNos" },
      { title: "Email", key: "email" },
      { title: "Home Address", key: "homeAddress" },
      { title: "Residential Address", key: "residentialAddress" },
      { title: "Residence Coordinates", key: "residenceCoordinates" },
      { title: "Address Details", key: "addressDetails" },
      { title: "Occupation", key: "occupation" },
      { title: "Work Type", key: "workType" },
      { title: "Business Category", key: "businessCategory" },
      { title: "Business Description", key: "businessDescriptions" },
      { title: "Designation", key: "designation" },
      { title: "Business Name", key: "businessName" },
      { title: "Business Location", key: "businessLocation" },
      { title: "Work Coordinates", key: "workCoordinates" },
      { title: "Marital Status", key: "maritalStatus" },
      { title: "Spouse Name", key: "spouseName" },
      { title: "Spouse Contact", key: "spouseContact" },
      { title: "NO Kin", key: "nOKin" },
      { title: "NO Kin Contact", key: "nOKinContact" },
      { title: "Id No Verified", key: "idNoVerified" },
      { title: "Profile Type", key: "profileType" },
      { title: "Phone Verified", key: "phoneVerified" },
      { title: "Branch", key: "branch" },
    ],
    children: [
      { id: "profile.profile.view", name: "View", to: { name: "profiles" } },
      {
        id: "profile.profile.new",
        name: "New",
        to: { name: "profile", params: { mode: 0 } },
      },
      {
        id: "profile.profile.edit",
        name: "Edit",
        to: { name: "profile", params: { mode: 1 } },
      },
      {
        id: "profile.profile.history",
        name: "History",
        to: { name: "profile", params: { mode: 2 } },
      },
    ],
  },
};
export default profileNav;
