import Profile from './Profile.vue'
import Profiles from './Profiles.vue'
import { navUtils } from 'saburi-vue-utils';
const profileNav = {

        routes: navUtils.allRoutes("profile", Profile, "profiles", Profiles, true),
        menu: {
                id: "profile.profile",
                title: "Profiles",
                component: Profile,
                path: "profiles",
                icon: "mdi-account-multiple",
                requires: navUtils.allRoles("profiles"),
                width: "1000px",

                editHeaders: [{ title: "Profile Type", key: "profileType" },
                { title: "First Name", key: "firstName" },
                { title: "Last Name", key: "lastName" },
                { title: "Other Names", key: "otherNames" },
                { title: "Birth Date", key: "birthDate", isDate: true },
                { title: "Gender", key: "gender" },
                { title: "Marital Status", key: "maritalStatusId" },
                { title: "Country", key: "countryId" },
                { title: "Spouse Name", key: "spouseName" },
                { title: "Spouse Contact", key: "spouseContact" },
                { title: "NO Kin", key: "nokin" },
                { title: "NO Kin Contact", key: "nokinContact" },
                { title: "Id Type", key: "idTypeId" },
                { title: "Id No", key: "idNo" },
                { title: "Primary Phone No", key: "primaryPhoneNo" },
                { title: "Other Phone Nos", key: "otherPhoneNos" },
                { title: "Email", key: "email" },
                { title: "Home Address", key: "homeAddress" },
                { title: "Residential Address", key: "residentialAddress", noWrap: "true" },
                { title: "Residence Coordinates", key: "residenceCoordinates" },
                { title: "Address Details", key: "addressDetails" },
                { title: "Join Date", key: "joinDate", isDate: true },
                { title: "Occupation", key: "occupationId" },
                { title: "Work Type", key: "workType" },
                { title: "Business Category", key: "businessCategoryId" },
                { title: "Business Description", key: "businessDescriptions" },
                { title: "Designation", key: "designation" },
                { title: "Business Name", key: "businessName" },
                { title: "Business Location", key: "businessLocation" },
                { title: "Work Coordinates", key: "workCoordinates" },
                { title: "Id No Verified", key: "idNoVerified" },
                { title: "Phone Verified", key: "phoneVerified" },
                { title: "Hidden", key: "hidden" },
                { title: "Actions", key: "actions" }],


                miniHeaders: [

                        { title: "Name", key: "display" },
                        { title: "Birth Date", key: "birthDate", isDate: true },
                        { title: "Gender", key: "gender" },
                        { title: "Primary Phone No", key: "primaryPhoneNo" },
                        { title: "Other Phone Nos", key: "otherPhoneNos" },
                        { title: "Email", key: "email" },
                        { title: "Home Address", key: "homeAddress" },
                        { title: "Address Details", key: "addressDetails" },
                     ],

                headers: [{
                        title: "Id",
                        align: "start",
                        // sortable: false,
                        key: "id",
                },
                { title: "Profile Type", key: "profileType" },
                { title: "First Name", key: "firstName" },
                { title: "Last Name", key: "lastName" },
                { title: "Other Names", key: "otherNames" },
                { title: "Birth Date", key: "birthDate", isDate: true },
                { title: "Gender", key: "gender" },
                { title: "Marital Status", key: "maritalStatus.display" },
                { title: "Spouse Name", key: "spouseName" },
                { title: "Spouse Contact", key: "spouseContact" },
                { title: "NO Kin", key: "nokin" },
                { title: "NO Kin Contact", key: "nokinContact" },
                { title: "Id Type", key: "idType?.display" },
                { title: "Id No", key: "idNo" },
                { title: "Primary Phone No", key: "primaryPhoneNo" },
                { title: "Other Phone Nos", key: "otherPhoneNos" },
                { title: "Email", key: "email" },
                { title: "Home Address", key: "homeAddress", noWrap: true },
                { title: "Residential Address", key: "residentialAddress", noWrap: true},
                { title: "Residence Coordinates", key: "residenceCoordinates" },
                { title: "Address Details", key: "addressDetails" },
                { title: "Join Date", key: "joinDate", isDate: true },
                { title: "Occupation", key: "occupationId" },
                { title: "Work Type", key: "workType" },
                { title: "Business Category", key: "businessCategoryId" },
                { title: "Business Description", key: "businessDescriptions" },
                { title: "Designation", key: "designation" },
                { title: "Business Name", key: "businessName" },
                { title: "Business Location", key: "businessLocation", noWrap: true },
                { title: "Work Coordinates", key: "workCoordinates" },
                { title: "Id No Verified", key: "idNoVerified" },
                { title: "Phone Verified", key: "phoneVerified" },
                { title: "Hidden", key: "hidden" },
                { title: "Branch", key: "branch", },
                { title: "Creation Date", key: "creationDate",isDateTime: true, },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true },
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],

                children: navUtils.allChildren('profile', 'profiles', 'profiles', false, 'profile'),
        }
}
export default profileNav;
