import Profile from './Profile.vue'
import Profiles from './Profiles.vue'
import navUtils from '@/nav/NavUtils';
const profileNav = {
        // routes: [
        //         {
        //                 path: '/profile/:mode',
        //                 name: 'profile',
        //                 component: Profile,
        //                 meta: { auth: true },
        //         },
        //         {
        //                 path: '/profiles',
        //                 name: 'profiles',
        //                 component: Profiles,
        //                 meta: { auth: true },
        //         },

        // ],
        routes: navUtils.allRoutes("profile", Profile, "profiles", Profiles, true),
        menu: {
                id: "profile.profile",
                title: "Profiles",
                component: Profile,
                path: "profiles",
                icon: "mdi-account-multiple",
                requires: navUtils.allRoles("profile"),
                width: "1000px",
               
                editHeaders: [{ title: "Profile Type", key: "profileType" },
                { title: "Photo", key: "photo" },
                { title: "First Name", key: "firstName" },
                { title: "Last Name", key: "lastName" },
                { title: "Other Names", key: "otherNames" },
                { title: "Birth Date", key: "birthDate", isDate: true },
                { title: "Gender", key: "gender" },
                { title: "Marital Status", key: "maritalStatusId" },
                { title: "Country", key: "countryId" },
                { title: "Spouse Name", key: "spouseName" },
                { title: "Spouse Contact", key: "spouseContact" },
                { title: "NO Kin", key: "nOKin" },
                { title: "NO Kin Contact", key: "nOKinContact" },
                { title: "Id Type", key: "idTypeId" },
                { title: "Id No", key: "idNo" },
                { title: "Primary Phone No", key: "primaryPhoneNo" },
                { title: "Other Phone Nos", key: "otherPhoneNos" },
                { title: "Email", key: "email" },
                { title: "Home Address", key: "homeAddress" },
                { title: "Residential Address", key: "residentialAddress" },
                { title: "Residence Coordinates", key: "residenceCoordinates" },
                { title: "Address Details", key: "addressDetails" },
                { title: "Join Date", key: "joinDate", isDate: true },
                { title: "Occupation", key: "occupationId" },
                { title: "Work Type", key: "workType" },
                { title: "Business Category", key: "businessCategoryId" },
                { title: "Business Description", key: "businessDescriptions" },
                { title: "Designation", key: "designation" },
                { title: "Business Name", key: "businessName" },
                { title: "Business Location", key: "businessLocation" },
                { title: "Work Coordinates", key: "workCoordinates" },
                { title: "Id No Verified", key: "idNoVerified" },
                { title: "Phone Verified", key: "phoneVerified" },
                { title: "Hidden", key: "hidden" },
                { title: "Actions", key: "actions" }],


                miniHeaders: [
                       
                        { title: "Name", key: "display" },
                        { title: "Birth Date", key: "birthDate", isDate: true },
                        { title: "Gender", key: "gender" },
                        { title: "Primary Phone No", key: "primaryPhoneNo" },
                        { title: "Other Phone Nos", key: "otherPhoneNos" },
                        { title: "Email", key: "email" },
                        { title: "Home Address", key: "homeAddress" },
                        { title: "Address Details", key: "addressDetails" },
                     ],
                
                headers: [{
                        title: "Id",
                        align: "start",
                        // sortable: false,
                        key: "id",
                },
                { title: "Profile Type", key: "profileType" },
                { title: "Photo", key: "photo" },
                { title: "First Name", key: "firstName" },
                { title: "Last Name", key: "lastName" },
                { title: "Other Names", key: "otherNames" },
                { title: "Birth Date", key: "birthDate", isDate: true },
                { title: "Gender", key: "gender" },
                { title: "Marital Status", key: "maritalStatusId" },
                { title: "Country", key: "countryId" },
                { title: "Spouse Name", key: "spouseName" },
                { title: "Spouse Contact", key: "spouseContact" },
                { title: "NO Kin", key: "nOKin" },
                { title: "NO Kin Contact", key: "nOKinContact" },
                { title: "Id Type", key: "idTypeId" },
                { title: "Id No", key: "idNo" },
                { title: "Primary Phone No", key: "primaryPhoneNo" },
                { title: "Other Phone Nos", key: "otherPhoneNos" },
                { title: "Email", key: "email" },
                { title: "Home Address", key: "homeAddress" },
                { title: "Residential Address", key: "residentialAddress" },
                { title: "Residence Coordinates", key: "residenceCoordinates" },
                { title: "Address Details", key: "addressDetails" },
                { title: "Join Date", key: "joinDate", isDate: true },
                { title: "Occupation", key: "occupationId" },
                { title: "Work Type", key: "workType" },
                { title: "Business Category", key: "businessCategoryId" },
                { title: "Business Description", key: "businessDescriptions" },
                { title: "Designation", key: "designation" },
                { title: "Business Name", key: "businessName" },
                { title: "Business Location", key: "businessLocation" },
                { title: "Work Coordinates", key: "workCoordinates" },
                { title: "Id No Verified", key: "idNoVerified" },
                { title: "Phone Verified", key: "phoneVerified" },
                { title: "Hidden", key: "hidden" },
                { title: "Branch", key: "branch", },
                { title: "Creation Date", key: "creationDate", label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true },
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
                // children: [{ id: "profile.profile.view", title: "View", icon: "mdi-table", to: { name: "profiles", } },
                // { id: "profile.profile.new", title: "New", icon: "mdi-plus-circle", to: { name: "profile", params: { mode: 0 } } },
                // { id: "profile.profile.edit", title: "Edit", icon: "mdi-pencil", to: { name: "profile", params: { mode: 1 } } },
                // { id: "profile.profile.history", title: "History", icon: "mdi-history", to: { name: "profile", params: { mode: 2 } } },
                // ]
                children: navUtils.allChildren('profile', 'profile', 'profiles', false),
        }
}
export default profileNav;
