#!/bin/bash

# Define variables
IMAGE_NAME="samburi/easyvalues"
TAG="2.0"
FULL_IMAGE="$IMAGE_NAME:$TAG"

echo "Building Docker image: $FULL_IMAGE"
docker build -t "$FULL_IMAGE" .

if [ $? -ne 0 ]; then
  echo "Docker build failed. Exiting..."
  exit 1
fi

echo "Pushing Docker image to registry: $FULL_IMAGE"
docker push "$FULL_IMAGE"

if [ $? -ne 0 ]; then
  echo "Docker push failed. Exiting..."
  exit 1
fi

echo "Docker image $FULL_IMAGE built and pushed successfully!"
