const lookupobjects = {
    BUSINESS_CATEGORY:1,
    MARITAL_STATUS: 2,
    STAFF_TITLE:3,
    OCCUPATION: 4,
    ID_TYPE:5,
    RELIGION:6,
    BUSINESS_SECTIONS: 9,
    PRICE_GROUP: 11,
    UNIT_MEASURE:12,
    ITEM_GROUP:13,
    BUSINESS_GROUP: 14,
    VAT_ITEM_GROUP: 15,
    VAT_BUSINESS_GROUP: 16,
    INVENTORY_GROUP:17,
    CUSTOMER_ACCOUNTS_CATEGORY:18,
    BANK_ACCOUNTS_GROUPS: 19,
    COLLATERAL_CATEGORIES: 20,
}

export default lookupobjects;