import Journal from './Journal.vue'
 import Journals from './Journals.vue'
 const journalNav={ routes:[
        {
                path: '/journal/:mode',
                name: 'journal',
                component: Journal,
                meta: { auth: true },
         },
         {
                path: '/journals',
                name: 'journals',
                component: Journals,
                meta: { auth: true },
         },
        
        ],
menu:{id: "accounting.journal",
        title: "Journals",
        component: Journal,
        path: "journals",
        width: "1000px",
editHeaders: [{ title: "Financial Period Id", key: "financialPeriodId"    },
{ title: "Tran Date", key: "tranDate"  , isDate: true },
{ title: "Description", key: "description"    },
{ title: "Reference No", key: "referenceNo"    },
{ title: "Currency", key: "currencyId"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Amount Words", key: "amountWords"    },
{ title: "Journal Details", key: "journalDetails"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "Financial Period Id", key: "financialPeriodId"    },
{ title: "Tran Date", key: "tranDate"  , isDate: true },
{ title: "Description", key: "description"    },
{ title: "Reference No", key: "referenceNo"    },
{ title: "Currency", key: "currencyId"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Amount Words", key: "amountWords"    },
{ title: "Journal Details", key: "journalDetails"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "accounting.journal.view", title: "View",  to:{ name: "journals", }},
{ id: "accounting.journal.new", title: "New",  to:{ name: "journal", params: {mode:0}}},
{ id: "accounting.journal.edit", title: "Edit",  to:{ name: "journal", params: {mode:1}}},
{ id: "accounting.journal.history", title: "History",  to:{ name: "journal", params: {mode:2}}},
]}
}
export default journalNav;
