
import Customer from './Customer.vue'
import Customers from './Customers.vue'
import { navUtils } from 'saburi-vue-utils';
const customerNav = {
      
     routes: navUtils.allRoutes('customer', Customer, 'customers', Customers, true),
       menu: {
              id: "customer.customer",
              title: "Customers",
              component: Customer,
              path: "customers",
              width: "1000px",
              icon: "mdi-account-outline",
              requires: navUtils.allRoles("customers"),
              miniHeaders: [{ title: "Profile Id", key: "id" },
              { title: "Customer Name", key: "customerName" },
              { title: "Phone No", key: "phoneNo" },
              { title: "Email", key: "email" },
              { title: "Address", key: "address" },
              { title: "Balance", key: "balance", isNumeric: true },
              ],

              editHeaders: [{ title: "Profile Id", key: "id" },
              { title: "Customer Name", key: "customerName" },
              { title: "Business Section", key: "customerTypeId" },
              { title: "Phone No", key: "phoneNo" },
              { title: "Email", key: "email" },
              { title: "Address", key: "address" },
              { title: "Price Group", key: "priceGroupId" },
              { title: "Default Sponsor", key: "defaultSponsor.id" },
              { title: "Can Sponsor", key: "canSponsor" },
              { title: "Sponsor Only", key: "sponsorOnly" },
              { title: "Allow Credit", key: "allowCredit" },
              { title: "Credit Limit", key: "creditLimit", isNumeric: true },
              { title: "Customer Accounts Group", key: "customerAccountsGroupId" },
              { title: "Balance", key: "balance", isNumeric: true },
              { title: "Hidden", key: "hidden" },
              { title: "Reference No", key: "referenceNo" },
              { title: "Actions", key: "actions" }],

              headers: [{
                     title: "Id",
                     align: "start",
                     // sortable: false,
                     key: "id",
              },
              { title: "Profile Id", key: "id" },
              { title: "Customer Name", key: "customerName" },
              { title: "Customer Group", key: "customerGroup.customerGroup" },
              { title: "Business Section", key: "customerTypeId" },
              { title: "Phone No", key: "phoneNo" },
              { title: "Balance", key: "balance", isNumeric: true },
              { title: "Address", key: "address" },
              { title: "Email", key: "email" },
              { title: "Price Group", key: "priceGroup" },
              { title: "Default Sponsor", key: "defaultSponsor.customerName" },
              { title: "Can Sponsor", key: "canSponsor" },
              { title: "Sponsor Only", key: "sponsorOnly" },
              { title: "Allow Credit", key: "allowCredit" },
              { title: "Credit Limit", key: "creditLimit", isNumeric: true },
              { title: "Hidden", key: "hidden" },
              { title: "Reference No", key: "referenceNo" },
              { title: "Branch", key: "branch", },
              { title: "Creation Date", key: "creationDate", label: "Creation Date", field: "creationDate", isDateTime: true },
              { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true },
              { title: "Created By", key: "createdBy", },
              { title: "Modified By", key: "modifiedBy", }],
              // children: [{ id: "customer.customer.view", title: "View", to: { name: "customers"}, icon: "mdi-table" }, 
              // { id: "customer.customer.new", title: "New", to: { name: "customer", params: { mode: 0 } }, icon: "mdi-plus-circle" },
              // { id: "customer.customer.edit", title: "Edit", to: { name: "customer", params: { mode: 1 } }, icon: "mdi-pencil" },
              // { id: "customer.customer.history", title: "History", to: { name: "customer", params: { mode: 2 } } , icon: "mdi-history" },
              // ]
              children: navUtils.allChildren("sales", "customers", "customers", false, "customer"),
       }
}
export default customerNav;
