import Engagement from './Engagement.vue'
 import Engagements from './Engagements.vue'
 const engagementNav={ routes:[
        {
                path: '/engagement/:mode',
                name: 'engagement',
                component: Engagement,
                meta: { auth: true },
         },
         {
                path: '/engagements',
                name: 'engagements',
                component: Engagements,
                meta: { auth: true },
         },

        ],
menu:{id: "customer.engagement",
        title: "Engagements",
        component: Engagement,
        path: "engagements",
        width: "1000px",
        midHeaders: [{ title: "Customer", key: "customer.id"    },
          { title: "Engagement Date", key: "engagementDate"  , isDate: true },
          { title: "Engagement Reason", key: "engagementReason"    },
          { title: "Engagement Mode", key: "engagementMode"    },
          { title: "Title", key: "title"    },
          { title: "Description", key: "description"    },
          { title: "Attending Personnel", key: "attendingPersonnel"    },
          { title: "Status", key: "status"    },
          { title: "Next Engagement Date", key: "nextEngagementDate"  , isDate: true },
          { title: "Expected Next Engagement Mode", key: "expectedNextEngagementMode"    },
          { title: "Parent Engagement", key: "parentEngagement.id"    },
          ],

editHeaders: [{ title: "Customer", key: "customer.id"    },
{ title: "Engagement Date", key: "engagementDate"  , isDate: true },
{ title: "Engagement Reason", key: "engagementReason"    },
{ title: "Engagement Mode", key: "engagementMode"    },
{ title: "Title", key: "title"    },
{ title: "Description", key: "description"    },
{ title: "Attending Personnel", key: "attendingPersonnel"    },
{ title: "Status", key: "status"    },
{ title: "Next Engagement Date", key: "nextEngagementDate"  , isDate: true },
{ title: "Expected Next Engagement Mode", key: "expectedNextEngagementMode"    },
{ title: "Parent Engagement", key: "parentEngagement.id"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "Customer", key: "customer.id"    },
{ title: "Engagement Date", key: "engagementDate"  , isDate: true },
{ title: "Engagement Reason", key: "engagementReason"    },
{ title: "Engagement Mode", key: "engagementMode"    },
{ title: "Title", key: "title"    },
{ title: "Description", key: "description"    },
{ title: "Attending Personnel", key: "attendingPersonnel"    },
{ title: "Status", key: "status"    },
{ title: "Next Engagement Date", key: "nextEngagementDate"  , isDate: true },
{ title: "Expected Next Engagement Mode", key: "expectedNextEngagementMode"    },
{ title: "Parent Engagement", key: "parentEngagement.id"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "customer.engagement.view", title: "View",  to:{ name: "engagements", }},
{ id: "customer.engagement.new", title: "New",  to:{ name: "engagement", params: {mode:0}}},
{ id: "customer.engagement.edit", title: "Edit",  to:{ name: "engagement", params: {mode:1}}},
{ id: "customer.engagement.history", title: "History",  to:{ name: "engagement", params: {mode:2}}},
]}
}
export default engagementNav;
