import Payment from "./Payment.vue";
import Payments from "./Payments.vue";
import { navUtils } from 'saburi-vue-utils';
const paymentNav = {
  // routes: [
  //   {
  //     path: "/payment/:mode",
  //     name: "payment",
  //     component: Payment,
  //     meta: { auth: true },
  //   },
  //   {
  //     path: "/payments",
  //     name: "payments",
  //     component: Payments,
  //     meta: { auth: true },
  //   },
  // ],
  routes: navUtils.allRoutes("payment", Payment, "payments", Payments, true),
  menu: {
    id: "creditor.payment",
    title: "Payments",
    component: Payment,
    path: "payments",
    requires: navUtils.allRoles("payments"),
    icon: "mdi-cash-multiple",
    width: "1000px",
    editHeaders: [
      { title: "Creditor", key: "creditor.id" },
      { title: "Name", key: "name" },
      { title: "Amount Due", key: "amoundDue", isNumeric: true },
      { title: "Pay Date", key: "payDate", isDate: true },
      { title: "Bank Account", key: "bankAccountName" },
      { title: "Bank Account Type", key: "bankAccountType" },
      { title: "Balance", key: "balance", isNumeric: true },
      { title: "Base Amount", key: "baseAmount", isNumeric: true },
      { title: "Discount", key: "discount", isNumeric: true },
      { title: "Withholding Tax", key: "withholdingTax", isNumeric: true },
      { title: "Currency", key: "currency" },
      { title: "Exchange Rate", key: "exchangeRate", isNumeric: true },
      { title: "Amount", key: "amount", isNumeric: true },
      { title: "Amount Words", key: "amountWords" },
      { title: "Amount Paid", key: "amountPaid", isNumeric: true },
      { title: "Description", key: "description" },
      { title: "Reference No", key: "referenceNo" },
      { title: "Actions", key: "actions" },
    ],
    headers: [
      {
        title: "Id",
        align: "start",
        // sortable: false,
        key: "id",
      },
      { title: "Creditor", key: "creditor.id" },
      { title: "Name", key: "creditor.name" },
      { title: "Amount Due", key: "amoundDue", isNumeric: true },
      { title: "Pay Date", key: "payDate", isDate: true },
      { title: "Bank Account", key: "bankAccount" },
      { title: "Bank Account Type", key: "bankAccountType" },
      { title: "Base Amount", key: "baseAmount", isNumeric: true },
      { title: "Discount", key: "discount", isNumeric: true },
      { title: "Withholding Tax", key: "withholdingTax", isNumeric: true },
      { title: "Currency", key: "currency" },
      { title: "Exchange Rate", key: "exchangeRate", isNumeric: true },
      { title: "Amount", key: "amount", isNumeric: true },
      { title: "Amount Words", key: "amountWords" },
      { title: "Amount Paid", key: "amountPaid", isNumeric: true },
      { title: "Description", key: "description" },
      { title: "Reference No", key: "referenceNo" },
      { title: "Gl Posted", key: "glPosted" },
      { title: "Bl Posted", key: "blPosted" },
      { title: "Branch", key: "branch" },
      {
        title: "Creation Date",
        key: "creationDate",
        label: "Creation Date",
        field: "creationDate",
        isDateTime: true,
      },
      {
        title: "Last Modified Date",
        key: "lastModifiedDate",
        isDateTime: true,
      },
      { title: "Created By", key: "createdBy" },
      { title: "Modified By", key: "modifiedBy" },
    ],
    // children: [
    //   { id: "creditor.payment.view", title: "View", to: { name: "payments" } },
    //   {
    //     id: "creditor.payment.new",
    //     title: "New",
    //     to: { name: "payment", params: { mode: 0 } },
    //   },
    //   {
    //     id: "creditor.payment.edit",
    //     title: "Edit",
    //     to: { name: "payment", params: { mode: 1 } },
    //   },
    //   {
    //     id: "creditor.payment.history",
    //     title: "History",
    //     to: { name: "payment", params: { mode: 2 } },
    //   },
    // ],
    children: navUtils.createViewChildren(
      "creditor",
      "payments",
      "payments",
      true,
      "payment"
    ),
  },
};
export default paymentNav;
