import Payment from './Payment.vue'
 import Payments from './Payments.vue'
 const paymentNav={ routes:[
        {
                path: '/payment/:mode',
                name: 'payment',
                component: Payment,
                meta: { auth: true },
         },
         {
                path: '/payments',
                name: 'payments',
                component: Payments,
                meta: { auth: true },
         },
        
        ],
menu:{id: "creditor.payment",
        title: "Payments",
        component: Payment,
        path: "payments",
        width: "1000px",
editHeaders: [{ title: "Creditor", key: "creditor.id"    },
{ title: "Name", key: "name"    },
{ title: "PayDate", key: "payDate"  , isDate: true },
{ title: "Bank Account", key: "bankAccountId"    },
{ title: "Bank Account Type", key: "bankAccountType"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Currency", key: "currencyId"    },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Amount Words", key: "amountWords"    },
{ title: "Description", key: "description"    },
{ title: "Reference No", key: "referenceNo"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "Creditor", key: "creditor.id"    },
{ title: "Name", key: "name"    },
{ title: "PayDate", key: "payDate"  , isDate: true },
{ title: "Bank Account", key: "bankAccountId"    },
{ title: "Bank Account Type", key: "bankAccountType"    },
{ title: "Base Amount", key: "baseAmount" ,isNumeric: true   },
{ title: "Currency", key: "currencyId"    },
{ title: "Exchange Rate", key: "exchangeRate" ,isNumeric: true   },
{ title: "Amount", key: "amount" ,isNumeric: true   },
{ title: "Amount Words", key: "amountWords"    },
{ title: "Description", key: "description"    },
{ title: "Reference No", key: "referenceNo"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "creditor.payment.view", title: "View",  to:{ name: "payments", }},
{ id: "creditor.payment.new", title: "New",  to:{ name: "payment", params: {mode:0}}},
{ id: "creditor.payment.edit", title: "Edit",  to:{ name: "payment", params: {mode:1}}},
{ id: "creditor.payment.history", title: "History",  to:{ name: "payment", params: {mode:2}}},
]}
}
export default paymentNav;
