import WriteOff from './WriteOff.vue'
const writeOffNav = {
        route: {
                path: '/writeOff/:mode',
                name: 'writeOff',
                component: WriteOff,
                meta: { auth: true },
        }, menu: {
                id: "sales.writeoff",
                name: "Write Offs",
                component: WriteOff,
                path: "writeoffs",
                width: "1000px",
                editHeaders: [{ text: "Write Off Date", value: "writeOffDate" },
                { text: "Customer Id", value: "customerId.displayKey" },
                { text: "Customer", value: "customer" },
                { text: "Write Off Type", value: "writeOffType" },
                { text: "Amount Tendered", value: "amountTendered" },
                { text: "Currency", value: "currencyId.displayKey" },
                { text: "Currency", value: "currency" },
                { text: "Exchange Rate", value: "exchangeRate" },
                { text: "Change Given", value: "changeGiven" },
                { text: "Amount", value: "amount" },
                { text: "AmountWords", value: "amountWords" },
                { text: "CL Post Status", value: "clPostStatus" },
                { text: "GL Post Status", value: "glPostStatus" },
                { text: "Amount Recovered", value: "amountRecovered" },
                { text: "WriteOff Invoices", value: "writeOffInvoices.displayKey" },
                { text: "Actions", value: "actions" }], headers: [{
                        text: "Id",
                        align: "start",
                        // sortable: false,
                        value: "id",
                },
                { text: "Write Off Date", value: "writeOffDate" },
                { text: "Customer Id", value: "customerId.displayKey" },
                { text: "Customer", value: "customer" },
                { text: "Write Off Type", value: "writeOffType" },
                { text: "Amount Tendered", value: "amountTendered" },
                { text: "Currency", value: "currencyId.displayKey" },
                { text: "Currency", value: "currency" },
                { text: "Exchange Rate", value: "exchangeRate" },
                { text: "Change Given", value: "changeGiven" },
                { text: "Amount", value: "amount" },
                { text: "AmountWords", value: "amountWords" },
                { text: "CL Post Status", value: "clPostStatus" },
                { text: "GL Post Status", value: "glPostStatus" },
                { text: "Amount Recovered", value: "amountRecovered" },
                { text: "WriteOff Invoices", value: "writeOffInvoices.displayKey" },
                ],
                children: [{ id: "sales.writeOff.new", name: "New", route: "writeOff", mode: 0 },
                { id: "sales.writeOff.edit", name: "Edit", route: "writeOff", mode: 1 },
                { id: "sales.writeOff.history", name: "History", route: "writeOff", mode: 2 },
                ]
        }
}
export default writeOffNav;
