import LoanProductCharges from "./LoanProductCharges.vue";
const loanProductChargesNav = {
  route: {
    path: "/loanproductcharge/:mode",
    name: "loanproductcharge",
    component: LoanProductCharges,
    meta: { auth: true },
  },
  menu: {
    id: "loan.loanproductcharges",
    title: "Loan Product Charges",
    component: LoanProductCharges,
    path: "loanproductcharges",
    width: "1000px",
    editHeaders: [
      {
        title: "Item Name",
        key: "itemName",
        label: "Item Name",
        field: "itemName",
      },
      {
        title: "Determining Method",
        key: "determiningMethod",
        label: "Determining Method",
        field: "determiningMethod",
      },
      {
        title: "Quantity",
        key: "quantity",
        label: "Quantity",
        field: "quantity",
        isNumeric: true,
      },
      {
        title: "Unit Cost",
        key: "unitCost",
        label: "Unit Cost",
        field: "unitCost",
        isNumeric: true,
      },
      {
        title: "Unit Price",
        key: "unitPrice",
        label: "Unit Price",
        field: "unitPrice",
        isNumeric: true,
      },
      {
        title: "Amount",
        key: "amount",
        label: "Amount",
        field: "amount",
        isNumeric: true,
      },
      {
        title: "Recurrent",
        key: "recurrent",
        label: "Recurrent",
        field: "recurrent",
      },
      { title: "Actions", key: "actions" },
    ],
    headers: [
      {
        title: "Id",
        align: "start",
        // sortable: false,
        key: "id",
      },
      {
        title: "Loan Product",
        key: "loanProduct",
        label: "Loan Product",
        field: "loanProduct",
        isNumeric: true,
      },
      { title: "tem Id", key: "itemId", label: "tem Id", field: "itemId" },
      {
        title: "ItemName",
        key: "itemName",
        label: "ItemName",
        field: "itemName",
      },
      {
        title: "Determining Method",
        key: "determiningMethod",
        label: "Determining Method",
        field: "determiningMethod",
      },
      {
        title: "Quantity",
        key: "quantity",
        label: "Quantity",
        field: "quantity",
        isNumeric: true,
      },
      {
        title: "Unit Cost",
        key: "unitCost",
        label: "Unit Cost",
        field: "unitCost",
        isNumeric: true,
      },
      {
        title: "Unit Price",
        key: "unitPrice",
        label: "Unit Price",
        field: "unitPrice",
        isNumeric: true,
      },
      {
        title: "Amount",
        key: "amount",
        label: "Amount",
        field: "amount",
        isNumeric: true,
      },
      {
        title: "Charge",
        key: "charge",
        label: "Charge",
        field: "charge",
        isNumeric: true,
      },
      {
        title: "Recurrent",
        key: "recurrent",
        label: "Recurrent",
        field: "recurrent",
      },
      { title: "Branch", key: "branch", label: "Branch", field: "branch" },
      {
        title: "Creation Date",
        key: "creationDate",
        label: "Creation Date",
        field: "creationDate",
        isDateTime: true,
      },
      {
        title: "Last Modified Date",
        key: "lastModifiedDate",
        isDateTime: true,
      },
      {
        title: "Created By",
        key: "createdBy",
        label: "Created By",
        field: "createdBy",
      },
      {
        title: "Modified By",
        key: "modifiedBy",
        label: "Modified By",
        field: "modifiedBy",
      },
    ],
    children: [
      {
        id: "loan.loanproductCharges.view",
        title: "View",
        to: {name: 'loanproductcharges'},
        mode: 0,
      },
      {
        id: "loan.loanProductCharges.new",
        title: "New",
        to: {name: 'loanproductcharge', params: {mode:0}},
        mode: 0,
      },
      {
        id: "loan.loanProductCharges.edit",
        title: "Edit",
        to: {name: 'loanproductcharge', params: {mode:1}},
      },
      {
        id: "loan.loanProductCharges.history",
        title: "History",
        to: {name: 'loanproductcharge', params: {mode:2}},
        mode: 2,
      },
    ],
  },
};
export default loanProductChargesNav;
