import Customer from './Customer.vue'
 import Customers from './Customers.vue'
 const customerNav={ routes:[
        {
                path: '/customer/:mode',
                name: 'customer',
                component: Customer,
                meta: { auth: true },
         },
         {
                path: '/customers',
                name: 'customers',
                component: Customers,
                meta: { auth: true },
         },

        ],
menu:{id: "customer.customer",
        title: "Customers",
        component: Customer,
        path: "customers",
        width: "1000px",
        miniHeaders: [{ title: "Profile Id", key: "id"    },
          { title: "Customer Name", key: "customerName"    },
         { title: "Phone No", key: "phoneNo"    },
          { title: "Email", key: "email"    },
          { title: "Address", key: "address"    },
          { title: "Balance", key: "balance" ,isNumeric: true   },
],

editHeaders: [{ title: "Profile Id", key: "id"    },
{ title: "Customer Name", key: "customerName"    },
{ title: "Business Section", key: "customerTypeId"    },
{ title: "Phone No", key: "phoneNo"    },
{ title: "Email", key: "email"    },
{ title: "Address", key: "address"    },
{ title: "Price Group", key: "priceGroupId"    },
{ title: "Default Sponsor", key: "defaultSponsor.id"    },
{ title: "Can Sponsor", key: "canSponsor"    },
{ title: "Sponsor Only", key: "sponsorOnly"    },
{ title: "Allow Credit", key: "allowCredit"    },
{ title: "Credit Limit", key: "creditLimit" ,isNumeric: true   },
{ title: "Customer Accounts Group", key: "customerAccountsGroupId"    },
{ title: "Balance", key: "balance" ,isNumeric: true   },
{ title: "Hidden", key: "hidden"    },
{ title: "Reference No", key: "referenceNo"    },
{title: "Actions", key: "actions"}],headers: [{
                title: "Id",
                align: "start",
                // sortable: false,
                key: "id",
            },
{ title: "Profile Id", key: "id"    },
{ title: "Customer Name", key: "customerName"    },
{ title: "Business Section", key: "customerTypeId"    },
{ title: "Phone No", key: "phoneNo"    },
{ title: "Email", key: "email"    },
{ title: "Address", key: "address"    },
{ title: "Price Group", key: "priceGroupId"    },
{ title: "Default Sponsor", key: "defaultSponsor.id"    },
{ title: "Can Sponsor", key: "canSponsor"    },
{ title: "Sponsor Only", key: "sponsorOnly"    },
{ title: "Allow Credit", key: "allowCredit"    },
{ title: "Credit Limit", key: "creditLimit" ,isNumeric: true   },
{ title: "Customer Accounts Group", key: "customerAccountsGroupId"    },
{ title: "Balance", key: "balance" ,isNumeric: true   },
{ title: "Hidden", key: "hidden"    },
{ title: "Reference No", key: "referenceNo"    },
 { title: "Branch", key: "branch",},
{ title: "Creation Date", key: "creationDate",  label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true},
                { title: "Created By", key: "createdBy", },
                { title: "Modified By", key: "modifiedBy", }],
children: [{ id: "customer.customer.view", title: "View",  to:{ name: "customers", }},
{ id: "customer.customer.new", title: "New",  to:{ name: "customer", params: {mode:0}}},
{ id: "customer.customer.edit", title: "Edit",  to:{ name: "customer", params: {mode:1}}},
{ id: "customer.customer.history", title: "History",  to:{ name: "customer", params: {mode:2}}},
]}
}
export default customerNav;
