import Item from './Item.vue'
 import Items from './Items.vue'
 const itemNav={ routes:[
        {
                path: '/item/:mode',
                name: 'item',
                component: Item,
                meta: { auth: true },
         },
         {
                path: '/items',
                name: 'items',
                component: Items,
                meta: { auth: true },
         },

        ], menu: {
                id: "lookup.item",
                title: "Items",
                component: Item,
                path: "items",
                width: "1000px",
                editHeaders: [{ title: "Item Category", key: "itemCategory.itemCategory", label: "Item Category", field: "itemCategory.itemCategory" },
                { title: "Item Name", key: "itemName", label: "Item Name", field: "itemName" },
                { title: "Unit Cost", key: "unitCost", label: "Unit Cost", field: "unitCost", isNumeric: true },
                { title: "Unit Price", key: "unitPrice", label: "Unit Price", field: "unitPrice", isNumeric: true },
                { title: "VAT Item Group", key: "vatItemGroup", label: "VAT Item Group", field: "vatItemGroup" },
                { title: "Inventory Group", key: "inventoryGroup", label: "Inventory Group", field: "inventoryGroup" },
                { title: "Measure Group", key: "measureGroup.measureGroupName", label: "Measure Group", field: "measureGroup.measureGroupName" },
                { title: "Edit Unit Cost", key: "editUnitCost", label: "Edit Unit Cost", field: "editUnitCost" },
                { title: "Edit Unit Price", key: "editUnitPrice", label: "Edit Unit Price", field: "editUnitPrice" },
                { title: "Hidden", key: "hidden", label: "Hidden", field: "hidden" },
               { title: "Actions", key: "actions" }],

               miniHeaders: [{ title: "Item Category", key: "itemCategory.itemCategory", label: "Item Category", field: "itemCategory.itemCategory" },
                { title: "Item Name", key: "itemName", label: "Item Name", field: "itemName" },
                { title: "Unit Cost", key: "unitCost", label: "Unit Cost", field: "unitCost", isNumeric: true },
                { title: "Unit Price", key: "unitPrice", label: "Unit Price", field: "unitPrice", isNumeric: true },
                { title: "VAT Item Group", key: "vatItemGroup", label: "VAT Item Group", field: "vatItemGroup" },
                { title: "Inventory Group", key: "inventoryGroup", label: "Inventory Group", field: "inventoryGroup" },
                { title: "Measure Group", key: "measureGroup.measureGroupName", label: "Measure Group", field: "measureGroup.measureGroupName" },
                { title: "Edit Unit Cost", key: "editUnitCost", label: "Edit Unit Cost", field: "editUnitCost" },
                { title: "Edit Unit Price", key: "editUnitPrice", label: "Edit Unit Price", field: "editUnitPrice" },
                { title: "Hidden", key: "hidden", label: "Hidden", field: "hidden" },
               ],
                headers: [{
                        title: "Id",
                        align: "start",
                        // sortable: false,
                        key: "id",
                },
                { title: "Item Category", key: "itemCategory.itemCategory"},
                {title: "Item Name", key: "itemName",},
                { title: "Unit Cost", key: "unitCost", label: "Unit Cost", field: "unitCost", isNumeric: true },
                { title: "Unit Price", key: "unitPrice", label: "Unit Price", field: "unitPrice", isNumeric: true },
                { title: "VAT Item Group", key: "vatItemGroup", label: "VAT Item Group", field: "vatItemGroup" },
                { title: "Inventory Group", key: "inventoryGroup", label: "Inventory Group", field: "inventoryGroup" },
                { title: "Measure Group", key: "measureGroup.measureGroupName", label: "Measure Group", field: "measureGroup.measureGroupName" },
                { title: "Edit Unit Cost", key: "editUnitCost", label: "Edit Unit Cost", field: "editUnitCost" },
                { title: "Edit Unit Price", key: "editUnitPrice", label: "Edit Unit Price", field: "editUnitPrice" },
                { title: "Edit Quantity", key: "editQuantity"},
                { title: "Hidden", key: "hidden", label: "Hidden", field: "hidden" },
                { title: "Branch", key: "branch", label: "Branch", field: "branch" },
                { title: "Creation Date", key: "creationDate", label: "Creation Date", field: "creationDate", isDateTime: true },
                { title: "Last Modified Date", key: "lastModifiedDate", isDateTime: true },
                { title: "Created By", key: "createdBy", label: "Created By", field: "createdBy" },
                { title: "Modified By", key: "modifiedBy", label: "Modified By", field: "modifiedBy" }],
                children: [
                  { id: "lookup.item.view", title: "View", to: {name:'items'} },
                  { id: "lookup.item.new", title: "New", to: {name:'item', params: {mode:0} } },
                { id: "lookup.item.edit", title: "Edit", to: {name:'item', params: {mode:1} } },
                { id: "lookup.item.history", title: "History", to: {name:'item', params: {mode:2} } },
                ]
        }
}
export default itemNav;
